dist: xenial
language: python
python: 3.7
install:

- pip install flake8 pytest-cov codecov
- pip install coveralls
- pip install -r requirements.txt


addons:
  sonarcloud:
    organization: "xfrnk2-github"
    token:
      secure: ${sonarcloud_token}
script:
- make test
- sonar-scanner 
- make cover
after_script:
- codecov --token=${codecov_token}