dist: xenial
language: python
python: 3.8.1
install:
- pip install -r requirements.txt
- pip install flake8 pytest-cov codecov
- pip install coveralls

addons:
  sonarcloud:
    organization: "xfrnk2-github"
    token:
      secure: ${sonarcloud_token}
script:
- make test
- sonar-scanner 
- make cover
after_script:
- codecov --token=${codecov_token}