# ln -s /bin/sh bash

dist: xenial
language: python
python: 3.8.1

before_install:
  - chmod +x LinuxWindowsScript.sh

install:
- make bootstrap

addons:
  sonarcloud:
    organization: "xfrnk2-github"
    token: ${sonarcloud_token}
script:
- make test
- sonar-scanner 
- make cover
after_script:
- codecov --token=${codecov_token}