 #!/bin/bash

dist: xenial
language: python
python: 3.8.1

before_install:
- chmod +x LinuxWindowsScript.sh

install:
- make bootstrap

script:
- make lint
- make test

addons:
  sonarcloud:
    organization: "xfrnk2-github"
    token: ${sonarcloud_token}


after_script:
- make cover
- sonar-scanner 
- codecov --token=${codecov_token}